### PR TITLE
Under debugging tools add my debugger entry into the ring. 

### PR DESCRIPTION
**Pull request by rocky**
In my biased opinion, trepan has features that I am not aware of in other debuggers. Namely: 

* extensive documentation in RestructuredText so it looks nice on pypy  as well as inside the debugger using terminal highlighting
* context-sensitive command completion
*  debugger macros that can be written in python
*  source-code syntax highlighting
*  stepping and filtering by event (call, return, c_call, c_return, line, exception ...)
*  a smart "eval" command

and more... See https://pypi.python.org/pypi/trepan/0.4.1

### CODE REVIEW

**Comment by vindarel** [comment]
Wow, this looks head-blowing. Macros to program our debugger ?! O_o

ps: will you do the same for the original's https://github.com/vinta/awesome-python#debugging-tools ?

**Comment by rocky** [comment]
https://github.com/vinta/awesome-python/pull/309

But double check I have this correct. I make lots of mistakes. That's why I work on debuggers.

**Comment by vindarel** [comment]
Ok, the link works, congrats !
By the way, ipdb has syntax highlighting of source code too (with the l command (minor L)).

**Comment by rocky** [comment]
It looks like ipdb is getting the syntax formatting via ipython which is interesting.

The way trepan handles syntax formatting is via pygments. The debugger uses pygments not only for python code, but also for CPython bytecode disasembly and for online debugger help. Debugger command help is stored in docstrings of each command class and uses ReStructuredText markup. In the debugger the strings are formatted to terminal escape sequences via a pygments terminal formatter. But since we use ReStructuredText as doc strings, it plays well with other Python source-code documentation tools.

At one time I had a debugger command to go into IPython. (You can go into a python shell). However the IPython interface changed and that broke the debugger code. I'm not a big enough IPython user track the interface changes. However if there are folks that want to reinstate this debugger command, I can help or those interested can retrieve the old code from previous git revisions.

**Pull request merged**
